site_name: XMC Tutorial

pages:
- Home: 'index.md'
- Basic:
    - Getting Started: GettingStartedXmc.md
    - Development Environment: DevelopmentEnvironment.md
    - CPU Subsystem: CpuSubsystem.md
    - Digital IOs: DigitalIos.md
    - PWM Basic: PwmBasic.md
    - ADC Basic: AdcBasic.md
    - DAC Basic: DacBasic.md
    - Interrupt: Interrupt.md
    - System Timer: SystemTimer.md
    - uC-Probe: uc-Probe.md

- LabBasic:
    - Getting Started Part-I: LabGettingStartedPart1.md
    - Getting Started Part-II: LabGettingStartedPart2.md
    - Check Dev Environment: LabCheckDevEnv.md

- Intermediate:
    - Counter: Counter.md
    - Timer: Timer.md
    - Real-time Clock: Rtc.md
    - Compare & Capture: Ccu8SliceConfig.md
    - DAC LUT: DacLut.md
    - Watchdog: Watchdog.md
    - DMA: DmaCh.md
    - Event: Eru.md
    - UART: Uart.md
    - USB: UsbdVcom.md

- LabIntermediate:
    - Counter: LabCounter.md
    - Timer: LabTimer.md
    
- Advanced:
    - Project Template: ProjectTemplate.md


theme: readthedocs

extra_javascript:
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

use_directory_urls: false
