site_name: XMC Tutorial

pages:
- Home: 'index.md'

- Basic:
    - Getting Started: GettingStartedXmc.md
    - Development Environment: DevelopmentEnvironment.md
    - CPU Subsystem: CpuSubsystem.md
    - Digital IOs: DigitalIos.md
    - PWM Basic: PwmBasic.md
    - ADC Basic: AdcBasic.md
    - DAC Basic: DacBasic.md
    - Interrupt: Interrupt.md
    - System Timer: SystemTimer.md
    - uC-Probe: uc-Probe.md

- LabBasic:
    - Check Dev Environment: LabCheckDevEnv.md
    - Getting Started Part-I: LabGettingStartedPart1.md
    - Getting Started Part-II: LabGettingStartedPart2.md
    - Digital IOs: LabDigitalIos.md
    - PWM Basic: LabPwmBasic.md
    - ADC Basic: LabAdcBasic.md
    - DAC Basic: LabDacBasic.md
    - Interrupt: LabNVIC.md
    - System Timer: LabSystemTimer.md

- Intermediate:
    - Counter: Counter.md
    - Timer: Timer.md
    - Capture: TimerCapture.md
    - Real-time Clock: Rtc.md
    - Watchdog(Optional): Watchdog.md
    - ADXL345 with SPI: ADXL345Spi.md
    - ADXL345 with I2C(Optional): ADXL345I2c.md
#    - Compare & Capture: Ccu8SliceConfig.md
#    - DAC LUT: DacLut.md
#    - DMA: DmaCh.md
#    - Event: Eru.md
#    - UART: Uart.md
#    - USB: UsbdVcom.md

- LabIntermediate:
    - Counter: LabCounter.md
    - Timer: LabTimer.md
    - Capture: LabTimerCapture.md
    - SPI: LabSpiMasterSlave.md
    - IIC(Optional): LabI2CMasterSlave.md
    - ADXL345 with SPI: LabADXL345Spi.md
    - ADXL345 with I2C(Optional): LabADXL345I2c.md

- Programming Background:
    - Functions & Program Design: ProgDesignFunction.md
    - Module Design & Multiple files: ProgModuleMultipleFiles.md
    - System Timer & Scheduler: ProgSystemTimerScheduler.md
    - Statemachine: ProgFsmBasic.md
    - Statemachine Example (Stop Light): ProgFsmStopLight.md

- Circuit Background:
    - Digital Signal Interfacing: DigitalInterface.md
    - Analog Signal Interfacing: AnalogInterface.md

#- Advanced:
#    - Project Template: ProjectTemplate.md

- Examples & Mini projects:
    - Final SignalGeneratorMonitor: LabSigGenMon.md
    - Ultrasonic Sensor: UltrasonicSensor.md

- Demo Projects - Signal Generator & Monitor
#    - Requirement Specification: SigGenMon_0ReqSpec.md
    - Design: SigGenMon_1Design.md
    - Test: SigGenMon_3TestReport.md

- References: 'References.md'

theme: readthedocs

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - mathjaxhelper.js
    
use_directory_urls: false
