<?xml version="1.0" encoding="ASCII"?>
<ResourceModel:App xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ResourceModel="http://www.infineon.com/Davex/Resource.ecore" name="SPI_MASTER" URI="http://resources/4.3.20/app/SPI_MASTER/0" description="Configures a USIC channel to perform transfer &amp; receive&#xA;operations through SPI protocol in Master mode." mode="NOTSHARABLE" version="4.3.20" minDaveVersion="4.0.0" instanceLabel="dhSPI_MASTER_0" appLabel="">
  <properties provideInit="true"/>
  <virtualSignals name="miso_0_input_stage" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dx0ins" hwSignal="dx0ins" hwResource="//@hwResources.0"/>
  <virtualSignals name="miso_1_input_stage" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dx3ins" hwSignal="dx3ins" hwResource="//@hwResources.0" required="false"/>
  <virtualSignals name="miso_2_input_stage" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dx4ins" hwSignal="dx4ins" hwResource="//@hwResources.0" required="false"/>
  <virtualSignals name="miso_3_input_stage" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dx5ins" hwSignal="dx5ins" hwResource="//@hwResources.0" required="false"/>
  <virtualSignals name="mosi_0_output_stage" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dout0" hwSignal="dout0" hwResource="//@hwResources.0"/>
  <virtualSignals name="mosi_1_output_stage" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dout1" hwSignal="dout1" hwResource="//@hwResources.0"/>
  <virtualSignals name="mosi_2_output_stage" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dout2" hwSignal="dout2" hwResource="//@hwResources.0"/>
  <virtualSignals name="mosi_3_output_stage" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dout3" hwSignal="dout3" hwResource="//@hwResources.0"/>
  <virtualSignals name="mosi_pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_mosi_0" hwSignal="pad" hwResource="//@hwResources.1" visible="true"/>
  <virtualSignals name="miso_pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_mosi_1" hwSignal="pad" hwResource="//@hwResources.2" visible="true"/>
  <virtualSignals name="mosi/miso[2]_pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_mosi_2" hwSignal="pad" hwResource="//@hwResources.3" required="false"/>
  <virtualSignals name="mosi/miso[3]_pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_mosi_3" hwSignal="pad" hwResource="//@hwResources.4" required="false"/>
  <virtualSignals name="sclk_out_pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_sclkoutpad" hwSignal="pad" hwResource="//@hwResources.5" visible="true"/>
  <virtualSignals name="sclk" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_sclkout" hwSignal="sclkout" hwResource="//@hwResources.0"/>
  <virtualSignals name="slave_select_0" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_0" hwResource="//@hwResources.0" solverVariableName="sv2" solverVariableValue="selo0"/>
  <virtualSignals name="slave_select_1" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_1" hwResource="//@hwResources.0" solverVariableName="sv3" solverVariableValue="selo1"/>
  <virtualSignals name="slave_select_2" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_2" hwResource="//@hwResources.0" required="false" solverVariableName="sv4" solverVariableValue=""/>
  <virtualSignals name="slave_select_3" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_3" hwResource="//@hwResources.0" required="false" solverVariableName="sv5" solverVariableValue=""/>
  <virtualSignals name="slave_select_4" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_4" hwResource="//@hwResources.0" required="false" solverVariableName="sv6" solverVariableValue=""/>
  <virtualSignals name="slave_select_5" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_5" hwResource="//@hwResources.0" required="false" solverVariableName="sv7" solverVariableValue=""/>
  <virtualSignals name="slave_select_6" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_6" hwResource="//@hwResources.0" required="false" solverVariableName="sv8" solverVariableValue=""/>
  <virtualSignals name="slave_select_7" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_7" hwResource="//@hwResources.0" required="false" solverVariableName="sv9" solverVariableValue=""/>
  <virtualSignals name="slave_select_0_pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_0_pad" hwSignal="pad" hwResource="//@hwResources.6" visible="true"/>
  <virtualSignals name="slave_select_1_pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_1_pad" hwSignal="pad" hwResource="//@hwResources.7" visible="true"/>
  <virtualSignals name="slave_select_2_pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_2_pad" hwSignal="pad" hwResource="//@hwResources.8" required="false"/>
  <virtualSignals name="slave_select_3_pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_3_pad" hwSignal="pad" hwResource="//@hwResources.9" required="false"/>
  <virtualSignals name="slave_select_4_pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_4_pad" hwSignal="pad" hwResource="//@hwResources.10" required="false"/>
  <virtualSignals name="slave_select_5_pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_5_pad" hwSignal="pad" hwResource="//@hwResources.11" required="false"/>
  <virtualSignals name="slave_select_6_pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_6_pad" hwSignal="pad" hwResource="//@hwResources.12" required="false"/>
  <virtualSignals name="slave_select_7_pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_7_pad" hwSignal="pad" hwResource="//@hwResources.13" required="false"/>
  <virtualSignals name="event_transmit_buffer" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_std_tx_int" hwSignal="transmit_buffer_int" hwResource="//@hwResources.0" required="false"/>
  <virtualSignals name="event_std_receive" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_std_rx_int" hwSignal="standard_receive_int" hwResource="//@hwResources.0" required="false"/>
  <virtualSignals name="event_receive_start" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_rx_start_int" hwSignal="receive_start_int" hwResource="//@hwResources.0" required="false"/>
  <virtualSignals name="event_alt_receive" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_alt_rx_int" hwSignal="alternate_receive_int" hwResource="//@hwResources.0" required="false"/>
  <virtualSignals name="event_protocol" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_protocol_specfic_int" hwSignal="protocol_specific_int" hwResource="//@hwResources.0" visible="true"/>
  <virtualSignals name="event_fifo_transmit" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_fifo_tx_int" hwSignal="standard_transmit_buffer_int" hwResource="//@hwResources.0"/>
  <virtualSignals name="event_fifo_std_receive" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_fifo_rx_int" hwSignal="standard_receive_buffer_int" hwResource="//@hwResources.0"/>
  <virtualSignals name="event_fifo_alt_receive" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_fifo_alt_rx_int" hwSignal="alternate_receive_buffer_int" hwResource="//@hwResources.0"/>
  <virtualSignals name="sr_transmit" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_interrupt_spi_master_tx" hwSignal="signal_in" hwResource="//@hwResources.14"/>
  <virtualSignals name="sr_receive" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_interrupt_spi_master_rx" hwSignal="signal_in" hwResource="//@hwResources.15"/>
  <virtualSignals name="sr_error" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_interrupt_spi_master_error" hwSignal="signal_in" hwResource="//@hwResources.16" required="false"/>
  <virtualSignals name="src_req" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dma_channel_rx_src_req" hwSignal="src_req" hwResource="//@hwResources.17"/>
  <virtualSignals name="source_trigger" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dlr_channel_rx_src_trigger" hwSignal="in" hwResource="//@hwResources.18" required="false"/>
  <virtualSignals name="dlr_out" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dlr_channel_rx_out" hwSignal="out" hwResource="//@hwResources.18" required="false"/>
  <virtualSignals name="dest_req" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dma_channel_tx_dest_req" hwSignal="dest_req" hwResource="//@hwResources.19" required="false"/>
  <virtualSignals name="destination_trigger" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dlr_channel_tx_dest_trigger" hwSignal="in" hwResource="//@hwResources.20" required="false"/>
  <virtualSignals name="dlr_out" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dlr_channel_tx_out" hwSignal="out" hwResource="//@hwResources.20" required="false"/>
  <virtualSignals name="event_dma_receive_end" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dma_channel_rx_event" hwSignal="dma_int" hwResource="//@hwResources.17" required="false"/>
  <virtualSignals name="event_dma_transmit_end" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dma_channel_tx_event" hwSignal="dma_int" hwResource="//@hwResources.19" required="false"/>
  <virtualSignals name="mosi_0_hw_o" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_mosi_0_hw_o" hwSignal="hw_o" hwResource="//@hwResources.1"/>
  <virtualSignals name="mosi_1_hw_o" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_mosi_1_hw_o" hwSignal="hw_o" hwResource="//@hwResources.2"/>
  <virtualSignals name="mosi_2_hw_o" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_mosi_2_hw_o" hwSignal="hw_o" hwResource="//@hwResources.3" required="false"/>
  <virtualSignals name="mosi_3_hw_o" URI="http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_mosi_3_hw_o" hwSignal="hw_o" hwResource="//@hwResources.4" required="false"/>
  <virtualSignals name="MOSI pin_signal" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_mosi_0" hwSignal="pin" hwResource="//@hwResources.21"/>
  <virtualSignals name="MISO pin_signal" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_mosi_1" hwSignal="pin" hwResource="//@hwResources.22"/>
  <virtualSignals name="MOSI\MISO_2 pin_signal" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_mosi_2" hwSignal="pin" hwResource="//@hwResources.23"/>
  <virtualSignals name="MOSI\MISO_3 pin_signal" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_mosi_3" hwSignal="pin" hwResource="//@hwResources.24"/>
  <virtualSignals name="SCLKOUT pin_signal" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_sclkoutpad" hwSignal="pin" hwResource="//@hwResources.25"/>
  <virtualSignals name="Slave Select 0 pin_signal" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_0_pad" hwSignal="pin" hwResource="//@hwResources.26"/>
  <virtualSignals name="Slave Select 1 pin_signal" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_1_pad" hwSignal="pin" hwResource="//@hwResources.27"/>
  <virtualSignals name="Slave Select 2 pin_signal" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_2_pad" hwSignal="pin" hwResource="//@hwResources.28"/>
  <virtualSignals name="Slave Select 3 pin_signal" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_3_pad" hwSignal="pin" hwResource="//@hwResources.29"/>
  <virtualSignals name="Slave Select 4 pin_signal" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_4_pad" hwSignal="pin" hwResource="//@hwResources.30"/>
  <virtualSignals name="Slave Select 5 pin_signal" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_5_pad" hwSignal="pin" hwResource="//@hwResources.31"/>
  <virtualSignals name="Slave Select 6 pin_signal" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_6_pad" hwSignal="pin" hwResource="//@hwResources.32"/>
  <virtualSignals name="Slave Select 7 pin_signal" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_7_pad" hwSignal="pin" hwResource="//@hwResources.33"/>
  <requiredApps URI="http://resources/4.3.20/app/SPI_MASTER/0/appres_clock" requiredAppName="CLOCK_XMC4" requiringMode="SHARABLE">
    <downwardMapList xsi:type="ResourceModel:App" href="../../CLOCK_XMC4/v4_0_22/CLOCK_XMC4_0.app#/"/>
  </requiredApps>
  <requiredApps URI="http://resources/4.3.20/app/SPI_MASTER/0/appres_cpu_ctrl" requiredAppName="CPU_CTRL_XMC4" requiringMode="SHARABLE">
    <downwardMapList xsi:type="ResourceModel:App" href="../../CPU_CTRL_XMC4/v4_0_14/CPU_CTRL_XMC4_0.app#/"/>
  </requiredApps>
  <requiredApps URI="http://resources/4.3.20/app/SPI_MASTER/0/appres_global_dma" requiredAppName="GLOBAL_DMA" required="false" requiringMode="SHARABLE"/>
  <hwResources name="Channel" URI="http://resources/4.3.20/app/SPI_MASTER/0/hwres_usic_channel" resourceGroupUri="peripheral/usic/*/channel/*" mResGrpUri="peripheral/usic/*/channel/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/USIC1/USIC1_1.dd#//@provided.43"/>
  </hwResources>
  <hwResources name="MOSI pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/hwres_port_pad_spi_mosi_0" resourceGroupUri="port/p/sv0/pad/*" solverVariable="true" mResGrpUri="port/p/sv0/pad/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/Port0/Port0_0.dd#//@provided.15"/>
    <solverVarMap index="2">
      <value variableName="sv0" solverValue="0"/>
    </solverVarMap>
    <solverVarMap index="2">
      <value variableName="sv0" solverValue="0"/>
    </solverVarMap>
  </hwResources>
  <hwResources name="MISO pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/hwres_port_pad_spi_mosi_1" resourceGroupUri="port/p/*/pad/*" mResGrpUri="port/p/*/pad/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/Port0/Port0_0.dd#//@provided.20"/>
  </hwResources>
  <hwResources name="MOSI\MISO_2 pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/hwres_port_pad_spi_mosi_2" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="MOSI\MISO_3 pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/hwres_port_pad_spi_mosi_3" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="SCLKOUT pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/hwres_port_pad_spi_sclkout" resourceGroupUri="port/p/*/pad/*" mResGrpUri="port/p/*/pad/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/Port0/Port0_0.dd#//@provided.11"/>
  </hwResources>
  <hwResources name="Slave Select 0 pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/hwres_port_pad_spi_ss_0" resourceGroupUri="port/p/*/pad/*" mResGrpUri="port/p/*/pad/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/Port0/Port0_0.dd#//@provided.37"/>
  </hwResources>
  <hwResources name="Slave Select 1 pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/hwres_port_pad_spi_ss_1" resourceGroupUri="port/p/*/pad/*" mResGrpUri="port/p/*/pad/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/Port0/Port0_0.dd#//@provided.41"/>
  </hwResources>
  <hwResources name="Slave Select 2 pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/hwres_port_pad_spi_ss_2" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Slave Select 3 pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/hwres_port_pad_spi_ss_3" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Slave Select 4 pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/hwres_port_pad_spi_ss_4" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Slave Select 5 pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/hwres_port_pad_spi_ss_5" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Slave Select 6 pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/hwres_port_pad_spi_ss_6" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="Slave Select 7 pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/hwres_port_pad_spi_ss_7" resourceGroupUri="" required="false" mResGrpUri="port/p/*/pad/*"/>
  <hwResources name="NVIC Node Tx" URI="http://resources/4.3.20/app/SPI_MASTER/0/hwres_cpu_nvic_interrupt_tx" resourceGroupUri="peripheral/cpu/0/nvic/interrupt/*" mResGrpUri="peripheral/cpu/0/nvic/interrupt/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/CPU/CPU_0.dd#//@provided.20"/>
  </hwResources>
  <hwResources name="NVIC Node Rx" URI="http://resources/4.3.20/app/SPI_MASTER/0/hwres_cpu_nvic_interrupt_rx" resourceGroupUri="peripheral/cpu/0/nvic/interrupt/*" mResGrpUri="peripheral/cpu/0/nvic/interrupt/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/CPU/CPU_0.dd#//@provided.24"/>
  </hwResources>
  <hwResources name="NVIC Node Error" URI="http://resources/4.3.20/app/SPI_MASTER/0/hwres_cpu_nvic_interrupt_error" resourceGroupUri="" required="false" mResGrpUri="peripheral/cpu/0/nvic/interrupt/*"/>
  <hwResources name="Receive DMA Channel" URI="http://resources/4.3.20/app/SPI_MASTER/0/hwres_dma_channel_rx" resourceGroupUri="" required="false" solverVariable="true" mResGrpUri="peripheral/sv1/0/*/*">
    <solverVarMap index="1">
      <value variableName="sv1" solverValue=""/>
    </solverVarMap>
    <solverVarMap index="1">
      <value variableName="sv1" solverValue=""/>
    </solverVarMap>
  </hwResources>
  <hwResources name="Receive DMA DLR" URI="http://resources/4.3.20/app/SPI_MASTER/0/hwres_dlr_channel_rx" resourceGroupUri="" required="false" mResGrpUri="peripheral/dlr/0/ch/*"/>
  <hwResources name="Transmit DMA Channel" URI="http://resources/4.3.20/app/SPI_MASTER/0/hwres_dma_channel_tx" resourceGroupUri="" required="false" solverVariable="true" mResGrpUri="peripheral/sv1/0/*/*">
    <solverVarMap index="1">
      <value variableName="sv1" solverValue=""/>
    </solverVarMap>
    <solverVarMap index="1">
      <value variableName="sv1" solverValue=""/>
    </solverVarMap>
  </hwResources>
  <hwResources name="Transmit DMA DLR" URI="http://resources/4.3.20/app/SPI_MASTER/0/hwres_dlr_channel_tx" resourceGroupUri="" required="false" mResGrpUri="peripheral/dlr/0/ch/*"/>
  <hwResources name="MOSI pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_hwres_port_pad_spi_mosi_0" resourceGroupUri="devicepackage/0/1" constraintType="GLOBAL_RESOURCE" mResGrpUri="devicepackage/0/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/DEVICEPACKAGE/DEVICEPACKAGE_0.dd#//@provided.6"/>
  </hwResources>
  <hwResources name="MISO pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_hwres_port_pad_spi_mosi_1" resourceGroupUri="devicepackage/0/2" constraintType="GLOBAL_RESOURCE" mResGrpUri="devicepackage/0/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/DEVICEPACKAGE/DEVICEPACKAGE_0.dd#//@provided.5"/>
  </hwResources>
  <hwResources name="MOSI\MISO_2 pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_hwres_port_pad_spi_mosi_2" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="MOSI\MISO_3 pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_hwres_port_pad_spi_mosi_3" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="SCLKOUT pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_hwres_port_pad_spi_sclkout" resourceGroupUri="devicepackage/0/3" constraintType="GLOBAL_RESOURCE" mResGrpUri="devicepackage/0/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/DEVICEPACKAGE/DEVICEPACKAGE_0.dd#//@provided.4"/>
  </hwResources>
  <hwResources name="Slave Select 0 pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_hwres_port_pad_spi_ss_0" resourceGroupUri="devicepackage/0/4" constraintType="GLOBAL_RESOURCE" mResGrpUri="devicepackage/0/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/DEVICEPACKAGE/DEVICEPACKAGE_0.dd#//@provided.18"/>
  </hwResources>
  <hwResources name="Slave Select 1 pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_hwres_port_pad_spi_ss_1" resourceGroupUri="devicepackage/0/100" constraintType="GLOBAL_RESOURCE" mResGrpUri="devicepackage/0/*">
    <downwardMapList xsi:type="ResourceModel:ResourceGroup" href="../../../HW_RESOURCES/DEVICEPACKAGE/DEVICEPACKAGE_0.dd#//@provided.17"/>
  </hwResources>
  <hwResources name="Slave Select 2 pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_hwres_port_pad_spi_ss_2" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="Slave Select 3 pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_hwres_port_pad_spi_ss_3" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="Slave Select 4 pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_hwres_port_pad_spi_ss_4" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="Slave Select 5 pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_hwres_port_pad_spi_ss_5" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="Slave Select 6 pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_hwres_port_pad_spi_ss_6" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <hwResources name="Slave Select 7 pin" URI="http://resources/4.3.20/app/SPI_MASTER/0/__pin_hwres_port_pad_spi_ss_7" resourceGroupUri="" required="false" mResGrpUri="devicepackage/0/*"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_std_rx_int/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dlr_channel_rx_src_trigger" systemDefined="true" sourceSignal="event_std_receive" targetSignal="source_trigger" required="false" srcVirtualSignal="//@virtualSignals.31" targetVirtualSignal="//@virtualSignals.42"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_alt_rx_int/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dlr_channel_rx_src_trigger" systemDefined="true" sourceSignal="event_alt_receive" targetSignal="source_trigger" required="false" srcVirtualSignal="//@virtualSignals.33" targetVirtualSignal="//@virtualSignals.42"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dlr_channel_rx_out/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dma_channel_rx_src_req" systemDefined="true" sourceSignal="dlr_out" targetSignal="src_req" required="false" srcVirtualSignal="//@virtualSignals.43" targetVirtualSignal="//@virtualSignals.41"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dma_channel_rx_event/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_global_dma_irq" systemDefined="true" sourceSignal="event_dma_receive_end" required="false" srcVirtualSignal="//@virtualSignals.47" containingProxySignal="true"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_rx_start_int/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dlr_channel_tx_dest_trigger" systemDefined="true" sourceSignal="event_receive_start" targetSignal="destination_trigger" required="false" srcVirtualSignal="//@virtualSignals.32" targetVirtualSignal="//@virtualSignals.45"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dlr_channel_tx_out/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dma_channel_tx_dest_req" systemDefined="true" sourceSignal="dlr_out" targetSignal="dest_req" required="false" srcVirtualSignal="//@virtualSignals.46" targetVirtualSignal="//@virtualSignals.44"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dma_channel_tx_event/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_global_dma_irq" systemDefined="true" sourceSignal="event_dma_transmit_end" required="false" srcVirtualSignal="//@virtualSignals.48" containingProxySignal="true"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dout0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_mosi_0" systemDefined="true" sourceSignal="mosi_0_output_stage" targetSignal="mosi_pin" srcVirtualSignal="//@virtualSignals.4" targetVirtualSignal="//@virtualSignals.8"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_mosi_0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dx0ins" systemDefined="true" sourceSignal="mosi_pin" targetSignal="miso_0_input_stage" required="false" srcVirtualSignal="//@virtualSignals.8" targetVirtualSignal="//@virtualSignals.0"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_mosi_1/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dx0ins" systemDefined="true" sourceSignal="miso_pin" targetSignal="miso_0_input_stage" srcVirtualSignal="//@virtualSignals.9" targetVirtualSignal="//@virtualSignals.0"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dout0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_mosi_0_hw_o" systemDefined="true" sourceSignal="mosi_0_output_stage" targetSignal="mosi_0_hw_o" required="false" srcVirtualSignal="//@virtualSignals.4" targetVirtualSignal="//@virtualSignals.49"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dout1/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_mosi_1_hw_o" systemDefined="true" sourceSignal="mosi_1_output_stage" targetSignal="mosi_1_hw_o" required="false" srcVirtualSignal="//@virtualSignals.5" targetVirtualSignal="//@virtualSignals.50"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dout2/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_mosi_2_hw_o" systemDefined="true" sourceSignal="mosi_2_output_stage" targetSignal="mosi_2_hw_o" required="false" srcVirtualSignal="//@virtualSignals.6" targetVirtualSignal="//@virtualSignals.51"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_dout3/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_mosi_3_hw_o" systemDefined="true" sourceSignal="mosi_3_output_stage" targetSignal="mosi_3_hw_o" required="false" srcVirtualSignal="//@virtualSignals.7" targetVirtualSignal="//@virtualSignals.52"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_sclkout/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_sclkoutpad" systemDefined="true" sourceSignal="sclk" targetSignal="sclk_out_pin" srcVirtualSignal="//@virtualSignals.13" targetVirtualSignal="//@virtualSignals.12"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_0_pad" systemDefined="true" sourceSignal="slave_select_0" targetSignal="slave_select_0_pin" srcVirtualSignal="//@virtualSignals.14" targetVirtualSignal="//@virtualSignals.22"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_1/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_1_pad" systemDefined="true" sourceSignal="slave_select_1" targetSignal="slave_select_1_pin" srcVirtualSignal="//@virtualSignals.15" targetVirtualSignal="//@virtualSignals.23"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_2/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_2_pad" systemDefined="true" sourceSignal="slave_select_2" targetSignal="slave_select_2_pin" required="false" srcVirtualSignal="//@virtualSignals.16" targetVirtualSignal="//@virtualSignals.24"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_3/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_3_pad" systemDefined="true" sourceSignal="slave_select_3" targetSignal="slave_select_3_pin" required="false" srcVirtualSignal="//@virtualSignals.17" targetVirtualSignal="//@virtualSignals.25"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_4/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_4_pad" systemDefined="true" sourceSignal="slave_select_4" targetSignal="slave_select_4_pin" required="false" srcVirtualSignal="//@virtualSignals.18" targetVirtualSignal="//@virtualSignals.26"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_5/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_5_pad" systemDefined="true" sourceSignal="slave_select_5" targetSignal="slave_select_5_pin" required="false" srcVirtualSignal="//@virtualSignals.19" targetVirtualSignal="//@virtualSignals.27"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_6/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_6_pad" systemDefined="true" sourceSignal="slave_select_6" targetSignal="slave_select_6_pin" required="false" srcVirtualSignal="//@virtualSignals.20" targetVirtualSignal="//@virtualSignals.28"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_7/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_7_pad" systemDefined="true" sourceSignal="slave_select_7" targetSignal="slave_select_7_pin" required="false" srcVirtualSignal="//@virtualSignals.21" targetVirtualSignal="//@virtualSignals.29"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_std_tx_int/http://resources/4.3.20/app/SPI_MASTER/0/vs_interrupt_spi_master_tx" systemDefined="true" sourceSignal="event_transmit_buffer" targetSignal="sr_transmit" required="false" srcVirtualSignal="//@virtualSignals.30" targetVirtualSignal="//@virtualSignals.38"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_fifo_tx_int/http://resources/4.3.20/app/SPI_MASTER/0/vs_interrupt_spi_master_tx" systemDefined="true" sourceSignal="event_fifo_transmit" targetSignal="sr_transmit" srcVirtualSignal="//@virtualSignals.35" targetVirtualSignal="//@virtualSignals.38"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_std_rx_int/http://resources/4.3.20/app/SPI_MASTER/0/vs_interrupt_spi_master_rx" systemDefined="true" sourceSignal="event_std_receive" targetSignal="sr_receive" required="false" srcVirtualSignal="//@virtualSignals.31" targetVirtualSignal="//@virtualSignals.39"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_alt_rx_int/http://resources/4.3.20/app/SPI_MASTER/0/vs_interrupt_spi_master_rx" systemDefined="true" sourceSignal="event_alt_receive" targetSignal="sr_receive" required="false" srcVirtualSignal="//@virtualSignals.33" targetVirtualSignal="//@virtualSignals.39"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_fifo_rx_int/http://resources/4.3.20/app/SPI_MASTER/0/vs_interrupt_spi_master_rx" systemDefined="true" sourceSignal="event_fifo_std_receive" targetSignal="sr_receive" srcVirtualSignal="//@virtualSignals.36" targetVirtualSignal="//@virtualSignals.39"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_fifo_alt_rx_int/http://resources/4.3.20/app/SPI_MASTER/0/vs_interrupt_spi_master_rx" systemDefined="true" sourceSignal="event_fifo_alt_receive" targetSignal="sr_receive" srcVirtualSignal="//@virtualSignals.37" targetVirtualSignal="//@virtualSignals.39"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_protocol_specfic_int/http://resources/4.3.20/app/SPI_MASTER/0/vs_interrupt_spi_master_error" systemDefined="true" sourceSignal="event_protocol" targetSignal="sr_error" required="false" srcVirtualSignal="//@virtualSignals.34" targetVirtualSignal="//@virtualSignals.40"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_mosi_0/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_mosi_0" systemDefined="true" sourceSignal="mosi_pin" targetSignal="MOSI pin_signal" srcVirtualSignal="//@virtualSignals.8" targetVirtualSignal="//@virtualSignals.53"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_mosi_0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_mosi_0" systemDefined="true" sourceSignal="MOSI pin_signal" targetSignal="mosi_pin" srcVirtualSignal="//@virtualSignals.53" targetVirtualSignal="//@virtualSignals.8"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_mosi_1/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_mosi_1" systemDefined="true" sourceSignal="miso_pin" targetSignal="MISO pin_signal" srcVirtualSignal="//@virtualSignals.9" targetVirtualSignal="//@virtualSignals.54"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_mosi_1/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_mosi_1" systemDefined="true" sourceSignal="MISO pin_signal" targetSignal="miso_pin" srcVirtualSignal="//@virtualSignals.54" targetVirtualSignal="//@virtualSignals.9"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_mosi_2/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_mosi_2" systemDefined="true" sourceSignal="mosi/miso[2]_pin" targetSignal="MOSI\MISO_2 pin_signal" srcVirtualSignal="//@virtualSignals.10" targetVirtualSignal="//@virtualSignals.55"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_mosi_2/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_mosi_2" systemDefined="true" sourceSignal="MOSI\MISO_2 pin_signal" targetSignal="mosi/miso[2]_pin" srcVirtualSignal="//@virtualSignals.55" targetVirtualSignal="//@virtualSignals.10"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_mosi_3/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_mosi_3" systemDefined="true" sourceSignal="mosi/miso[3]_pin" targetSignal="MOSI\MISO_3 pin_signal" srcVirtualSignal="//@virtualSignals.11" targetVirtualSignal="//@virtualSignals.56"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_mosi_3/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_mosi_3" systemDefined="true" sourceSignal="MOSI\MISO_3 pin_signal" targetSignal="mosi/miso[3]_pin" srcVirtualSignal="//@virtualSignals.56" targetVirtualSignal="//@virtualSignals.11"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_sclkoutpad/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_sclkoutpad" systemDefined="true" sourceSignal="sclk_out_pin" targetSignal="SCLKOUT pin_signal" srcVirtualSignal="//@virtualSignals.12" targetVirtualSignal="//@virtualSignals.57"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_sclkoutpad/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_sclkoutpad" systemDefined="true" sourceSignal="SCLKOUT pin_signal" targetSignal="sclk_out_pin" srcVirtualSignal="//@virtualSignals.57" targetVirtualSignal="//@virtualSignals.12"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_0_pad/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_0_pad" systemDefined="true" sourceSignal="slave_select_0_pin" targetSignal="Slave Select 0 pin_signal" srcVirtualSignal="//@virtualSignals.22" targetVirtualSignal="//@virtualSignals.58"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_0_pad/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_0_pad" systemDefined="true" sourceSignal="Slave Select 0 pin_signal" targetSignal="slave_select_0_pin" srcVirtualSignal="//@virtualSignals.58" targetVirtualSignal="//@virtualSignals.22"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_1_pad/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_1_pad" systemDefined="true" sourceSignal="slave_select_1_pin" targetSignal="Slave Select 1 pin_signal" srcVirtualSignal="//@virtualSignals.23" targetVirtualSignal="//@virtualSignals.59"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_1_pad/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_1_pad" systemDefined="true" sourceSignal="Slave Select 1 pin_signal" targetSignal="slave_select_1_pin" srcVirtualSignal="//@virtualSignals.59" targetVirtualSignal="//@virtualSignals.23"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_2_pad/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_2_pad" systemDefined="true" sourceSignal="slave_select_2_pin" targetSignal="Slave Select 2 pin_signal" srcVirtualSignal="//@virtualSignals.24" targetVirtualSignal="//@virtualSignals.60"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_2_pad/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_2_pad" systemDefined="true" sourceSignal="Slave Select 2 pin_signal" targetSignal="slave_select_2_pin" srcVirtualSignal="//@virtualSignals.60" targetVirtualSignal="//@virtualSignals.24"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_3_pad/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_3_pad" systemDefined="true" sourceSignal="slave_select_3_pin" targetSignal="Slave Select 3 pin_signal" srcVirtualSignal="//@virtualSignals.25" targetVirtualSignal="//@virtualSignals.61"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_3_pad/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_3_pad" systemDefined="true" sourceSignal="Slave Select 3 pin_signal" targetSignal="slave_select_3_pin" srcVirtualSignal="//@virtualSignals.61" targetVirtualSignal="//@virtualSignals.25"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_4_pad/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_4_pad" systemDefined="true" sourceSignal="slave_select_4_pin" targetSignal="Slave Select 4 pin_signal" srcVirtualSignal="//@virtualSignals.26" targetVirtualSignal="//@virtualSignals.62"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_4_pad/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_4_pad" systemDefined="true" sourceSignal="Slave Select 4 pin_signal" targetSignal="slave_select_4_pin" srcVirtualSignal="//@virtualSignals.62" targetVirtualSignal="//@virtualSignals.26"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_5_pad/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_5_pad" systemDefined="true" sourceSignal="slave_select_5_pin" targetSignal="Slave Select 5 pin_signal" srcVirtualSignal="//@virtualSignals.27" targetVirtualSignal="//@virtualSignals.63"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_5_pad/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_5_pad" systemDefined="true" sourceSignal="Slave Select 5 pin_signal" targetSignal="slave_select_5_pin" srcVirtualSignal="//@virtualSignals.63" targetVirtualSignal="//@virtualSignals.27"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_6_pad/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_6_pad" systemDefined="true" sourceSignal="slave_select_6_pin" targetSignal="Slave Select 6 pin_signal" srcVirtualSignal="//@virtualSignals.28" targetVirtualSignal="//@virtualSignals.64"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_6_pad/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_6_pad" systemDefined="true" sourceSignal="Slave Select 6 pin_signal" targetSignal="slave_select_6_pin" srcVirtualSignal="//@virtualSignals.64" targetVirtualSignal="//@virtualSignals.28"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_7_pad/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_7_pad" systemDefined="true" sourceSignal="slave_select_7_pin" targetSignal="Slave Select 7 pin_signal" srcVirtualSignal="//@virtualSignals.29" targetVirtualSignal="//@virtualSignals.65"/>
  <connections URI="http://resources/4.3.20/app/SPI_MASTER/0/http://resources/4.3.20/app/SPI_MASTER/0/__pin_vs_spi_master_slave_select_7_pad/http://resources/4.3.20/app/SPI_MASTER/0/vs_spi_master_slave_select_7_pad" systemDefined="true" sourceSignal="Slave Select 7 pin_signal" targetSignal="slave_select_7_pin" srcVirtualSignal="//@virtualSignals.65" targetVirtualSignal="//@virtualSignals.29"/>
</ResourceModel:App>
